language: node_js
node_js:
  - "stable"
addons: code_climate
env:
  global:
    - CC_TEST_REPORTER_ID=2ae653f08bb4a1810f7bc1eff24c04575ae60b69bbe3d6b58c597faafdcd88cf
cache:
  directories:
  - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test -- --coverage # Include coverage when running tests
  - npm run build
after_script: # Upload coverage reports 
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT